name: Generate Pkldoc

on:
  push:
    branches:
      - main
    paths:
      - 'Sources/ArcCLI/Resources/ArcConfiguration.pkl'
      - 'Sources/ArcCLI/Resources/doc-package-info.pkl'
  workflow_dispatch:

# Grant permissions required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Generate and Deploy Pkldoc
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pkldoc
        run: |
          PKLDOC_VERSION="0.30.2"
          PKLDOC_URL="https://github.com/apple/pkl/releases/download/${PKLDOC_VERSION}/pkldoc-linux-amd64"
          curl -L -o pkldoc "$PKLDOC_URL"
          chmod +x pkldoc
          sudo mv pkldoc /usr/local/bin/
      - name: Generate Pkldoc
        run: 
          mkdir -p docs/pkldoc
          pkldoc \
            --output-dir docs/pkldoc \
            Sources/ArcCLI/Resources/doc-package-info.pkl \
            Sources/ArcCLI/Resources/ArcConfiguration.pkl
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/pkldoc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4